# Generated by Django 2.0.2 on 2018-05-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=30)),
                ('datum', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('besedilo', models.CharField(max_length=2000)),
            ],
        ),
    ]
